/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GoldsInventory;

import Business.EcoSystem;
import Business.Organization.Organization;
import Business.WorkQueue.AppointmentRequest;
import Business.WorkQueue.InventoryQueue;
import Business.WorkQueue.InventoryRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class CheckInventoryRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckInventoryRequestJPanel
     */
    JPanel userProcessContainer;
    Organization organization;
    EcoSystem system;
    InventoryQueue intQ;
    public CheckInventoryRequestJPanel(JPanel userProcessContainer, Organization organization, EcoSystem system,InventoryQueue intQ) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.system = system;
        this.intQ = intQ;
        this.organization = organization;
        populateTable();
    }
   
    public void populateTable(){
        
          DefaultTableModel model = (DefaultTableModel) apptRequestJTable.getModel();
        model.setRowCount(0);
        
        for(InventoryRequest ar : intQ.getinventoryRequestList()){
            if(ar.getSender() == organization){
                    Object[] row = new Object[6];
                    row[0] = ar.getId();
                    row[1] = ar.getStatus();
                    row[2] = ar.getSender();
                    row[3] = ar.getReceiver();
                    row[4] = ar.getRequestDate();
                    row[5] = ar.getMessage();
                    model.addRow(row);
            }    
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        apptRequestJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        apptRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Status", "Sender", "Receiver", "Request Date", "Message "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(apptRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 700, 280));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("Check Inventory Request :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 270, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable apptRequestJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
