/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AnytimeInventory;
import Business.EcoSystem;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author dell
 */
public class AnyTimeInventoryWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GoldsInventory
     */
    JPanel userProcessContainer;
    Organization organization;
    EcoSystem system;
    public AnyTimeInventoryWorkAreaJPanel(JPanel userProcessContainer, Organization organization, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.system = system;
    }
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ViewInventoryButton = new javax.swing.JButton();
        RequestInventoryButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CheckRequestStatusButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel1.setText("AnyTime Inventory Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 29, 500, 40));

        ViewInventoryButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ViewInventoryButton.setText("View Inventory ");
        ViewInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewInventoryButtonActionPerformed(evt);
            }
        });
        add(ViewInventoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 180, 40));

        RequestInventoryButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RequestInventoryButton.setText("Request Inventory");
        RequestInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestInventoryButtonActionPerformed(evt);
            }
        });
        add(RequestInventoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 180, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Organization Tasks :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 150, 30));

        CheckRequestStatusButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckRequestStatusButton.setText("Check Request Status");
        CheckRequestStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckRequestStatusButtonActionPerformed(evt);
            }
        });
        add(CheckRequestStatusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 190, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void ViewInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewInventoryButtonActionPerformed
        // TODO add your handling code here:
        
        ViewInventoryJPanel vijp = new ViewInventoryJPanel(userProcessContainer, organization, system);
        userProcessContainer.add("ViewInventoryJPanel", vijp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ViewInventoryButtonActionPerformed

    private void RequestInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestInventoryButtonActionPerformed
        // TODO add your handling code here:
        RequestInventoryJPanel rijp = new RequestInventoryJPanel(userProcessContainer, organization, system);
        userProcessContainer.add("RequestInventoryJPanel", rijp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_RequestInventoryButtonActionPerformed

    private void CheckRequestStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckRequestStatusButtonActionPerformed
        // TODO add your handling code here:
        CheckInventoryRequestJPanel cijp = new CheckInventoryRequestJPanel(userProcessContainer, organization, system);
        userProcessContainer.add("CheckInventoryRequestJPanel", cijp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_CheckRequestStatusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckRequestStatusButton;
    private javax.swing.JButton RequestInventoryButton;
    private javax.swing.JButton ViewInventoryButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
