/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AnytimeInventory;

import userinterface.CrossInventory.*;
import userinterface.GoldsInventory.*;
import Business.EcoSystem;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author dell
 */
public class RequestInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageInventoryJPanel
     */
    JPanel userProcessContainer;
    Organization organization;
    EcoSystem system;
    public RequestInventoryJPanel(JPanel userProcessContainer, Organization organization, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.system = system;
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RequestInventoryJButton = new javax.swing.JButton();
        enterpriseLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaRequest = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RequestInventoryJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RequestInventoryJButton.setText("Request for Inventory");
        RequestInventoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestInventoryJButtonActionPerformed(evt);
            }
        });
        add(RequestInventoryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 220, 30));

        enterpriseLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        enterpriseLabel3.setText("Request Inventory :");
        add(enterpriseLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, 40));

        jtxtAreaRequest.setColumns(20);
        jtxtAreaRequest.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 220, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("Request Inventory Work Area :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 270, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 90, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void RequestInventoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestInventoryJButtonActionPerformed

      
    }//GEN-LAST:event_RequestInventoryJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RequestInventoryJButton;
    private javax.swing.JLabel enterpriseLabel3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtxtAreaRequest;
    // End of variables declaration//GEN-END:variables
}
