/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Golds;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.WorkQueue.InventoryQueue;
import Business.WorkQueue.InventoryRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class GoldsInventoryRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GoldsInventoryRequestJPanel1
     */
    JPanel userProcessContainer;
    Organization organization;
    EcoSystem system;
    Enterprise enterprise;
    InventoryQueue intQ;
    public GoldsInventoryRequestJPanel(JPanel userProcessContainer, Organization organization,EcoSystem system , Enterprise enterprise,InventoryQueue intQ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.system = system;
        this.enterprise = enterprise;
        this.intQ = intQ;
        populatetable();
    }
        public void populatetable(){
            DefaultTableModel model = (DefaultTableModel) inventoryRequestJTable.getModel();
        model.setRowCount(0);
        System.out.println("I went Inside yayyyy once");
        System.out.println(system.getIntQ().getinventoryRequestList().size());
        for(InventoryRequest ar : intQ.getinventoryRequestList()){
            if(ar.getReceiver() == enterprise && ar.getStatus() == "Pending"){
                    System.out.println("I went Inside yayyyy");
                    Object[] row = new Object[5];
                    row[0] = ar.getId();
                    row[1] = ar.getStatus();
                    row[2] = ar.getSender();
                    row[3] = ar.getReceiver();
                    row[4] = ar.getRequestDate();
                    model.addRow(row);
                     System.out.println("I went Inside yayyyy twice");
            }    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        viewRequestDetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryRequestJTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Golds Inventory Requests");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 410, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 100, 30));

        viewRequestDetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewRequestDetails.setText("View Request Details");
        viewRequestDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequestDetailsActionPerformed(evt);
            }
        });
        add(viewRequestDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 170, 30));

        inventoryRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Status", "Sender", "Receiver", "Request Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(inventoryRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 840, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewRequestDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequestDetailsActionPerformed

        int selectedRow = inventoryRequestJTable.getSelectedRow();
        //int i = 0;
        if(selectedRow >=0){
            int id = (int) inventoryRequestJTable.getValueAt(selectedRow, 0);
            System.out.println(id);
            InventoryRequest apptr = system.getIntQ().getinventoryRequest(id);
            System.out.println(apptr.getId());
            GoldsInventoryDetailsJPanel panel = new GoldsInventoryDetailsJPanel(userProcessContainer, apptr, system, organization,enterprise);
            userProcessContainer.add("GoldsInventoryDetailsJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }else{
            JOptionPane.showMessageDialog(null, "Please select an Appointment to view its details","Information",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_viewRequestDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable inventoryRequestJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewRequestDetails;
    // End of variables declaration//GEN-END:variables
}
