/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author dell
 */
public class ContainerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ContainerJPanel
     */
    public ContainerJPanel() {
        initComponents();
        
        pictureJLabel.setIcon(new ImageIcon(new ImageIcon("C:\\Users\\dell\\AED\\thefitapp\\182186905.jpg").getImage().getScaledInstance(1200, 900, Image.SCALE_DEFAULT)));
//        ImageIcon image = new ImageIcon("C:\\Users\\dell\\AED\\aed-project\\TheFitApp\\182186905.jpg");
//        //Image image1 = image.getImage();
//        Image img = image.getImage().getScaledInstance(pictureJLabel.getWidth(), pictureJLabel.getHeight(),Image.SCALE_SMOOTH);
//        ImageIcon imgIcon = new ImageIcon(img);
//        pictureJLabel.setIcon(imgIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictureJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 153));

        pictureJLabel.setBackground(new java.awt.Color(0, 51, 204));
        pictureJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pictureJLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\AED\\aed-project\\182186905.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pictureJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pictureJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pictureJLabel;
    // End of variables declaration//GEN-END:variables
}
