/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NewUser;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.NewUser.NewUser;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.WorkQueue.AppointmentQueue;
import Business.WorkQueue.AppointmentRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author keyur_donga
 */
public class BookAppointmentJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private NewUser nu;
    private EcoSystem system;
    /**
     * Creates new form BookAppointmentJPanel
     */
    public BookAppointmentJPanel(JPanel userProcessContainer, NewUser nu, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.nu = nu;
        this.system = system;
        
        popOrganizationComboBox();
    }
    
    public void popOrganizationComboBox() {
        organizationJComboBox.removeAllItems();
        for(Network nt : system.getNetworkList()){
            for(Enterprise enterprise : nt.getEnterpriseDirectory().getEnterpriseList()){
                organizationJComboBox.addItem(enterprise.toString());
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        organizationJComboBox = new javax.swing.JComboBox<>();
        enterpriseLabel3 = new javax.swing.JLabel();
        enterpriseLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaRequest = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Request for Appointment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 220, 30));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", " " }));
        add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 220, 30));

        enterpriseLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        enterpriseLabel3.setText("Special request :");
        add(enterpriseLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 150, 30));

        enterpriseLabel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        enterpriseLabel4.setText("Select Gym :");
        add(enterpriseLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 120, 30));

        jtxtAreaRequest.setColumns(20);
        jtxtAreaRequest.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NewUserWorkAreaJPanel nujp = (NewUserWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        for(Network nt : system.getNetworkList()){    
            for(Enterprise enterprise : nt.getEnterpriseDirectory().getEnterpriseList()){
                if(enterprise.toString() == organizationJComboBox.getSelectedItem()){
                    String message = jtxtAreaRequest.getText();

                    AppointmentRequest ar = new AppointmentRequest();
                    ar.setMessage(message);
                    ar.setSender(nu);
                    ar.setReceiver(enterprise);
                    ar.setStatus("Pending");
                    system.getApptQ().addApptRequest(ar);
                    JOptionPane.showMessageDialog(null, "Successfully requested for an appointment", "Information", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel3;
    private javax.swing.JLabel enterpriseLabel4;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtxtAreaRequest;
    private javax.swing.JComboBox<String> organizationJComboBox;
    // End of variables declaration//GEN-END:variables
}
