/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NewUser;

import Business.EcoSystem;
import Business.NewUser.NewUser;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author keyur_donga
 */
public class NewUserWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private NewUser nu;
    private EcoSystem system;
    /**
     * Creates new form NewUserWorkAreaJPanel
     */
    public NewUserWorkAreaJPanel(JPanel container, NewUser nu, EcoSystem system) {
        initComponents();
        this.userProcessContainer = container;
        this.nu = nu;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Book an Appointment with a GYM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 230, 40));

        jButton3.setText("Check status of Past Appointments");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 230, 40));

        jButton4.setText("View Personal Details");
        jButton4.setEnabled(false);
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 230, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BookAppointmentJPanel bajp = new BookAppointmentJPanel(userProcessContainer, nu, system);
        userProcessContainer.add("BookAppointmentJPanel", bajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CheckAppointmentStatusJPanel casjp = new CheckAppointmentStatusJPanel(userProcessContainer, nu, system);
        userProcessContainer.add("CheckAppointmentStatusJPanel", casjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
